config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "projects#index"

  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash.now[:alert] = "Project has not been created"
      render "new"
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  private

  def project_params
    params.require(:project).permit(:name,:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ")
      end
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <% if content_for?(:title) %>
        <%= yield(:title) %>
      <% else %>
        Ticketee
      <% end -%>
    </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |key, message| %>
    <div><%= message  %></div>
  <% end -%>
  
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= form_for @project do |f| -%>
<% if @project.errors.any? %>
  <div id = "error explanation">
    <h2>
      <%= pluralize(@project.errors.count, "error")  %>
      prohibited this project from being saved:
    </h2>

    <ul>
      <% @project.errors.full_messages.each do |msg|  %>
      <li>
        <%= msg  %>
      </li>
      <% end -%>
    </ul>
  </div>
<% end -%>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>

  <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects")  %>
<h1><%= @project.name  %></h1>
<p><%= @project.description  %></p>